language: node_js
node_js:
  - '9.8.0'
cache:
  directories:
    - node_modules
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules
before_install:
  - npm i -g npm@5.7.1
script:
  - npm test
  - npm run build
